export const extensionLanguageMap = {
  rs: 'rust',
  ts: 'typescript',
  js: 'javascript',
  py: 'python',
  json: 'json',
  yml: 'yaml',
  yaml: 'yaml',
};

export const languageExtensionMap = {
  typescript: 'ts',
  javascript: 'js',
  python: 'py',
  c: 'c',
  cpp: 'cpp',
  csharp: 'cs',
  java: 'java',
  ruby: 'rb',
  python3: 'py',
  php: 'php',
  html: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  json: 'json',
  yaml: 'yaml',
  markdown: 'md',
  xml: 'xml',
  bash: 'sh',
  shell: 'sh',
  sql: 'sql',
  swift: 'swift',
  kotlin: 'kt',
  go: 'go',
  rust: 'rs',
  haskell: 'hs',
  typescriptreact: 'tsx',
  javascriptreact: 'jsx',
};
